# Enable USB and Bluetooth connectivity
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y

# Battery reporting configuration
CONFIG_ZMK_BATTERY_REPORTING=y

# Bluetooth connection interval settings (in units of 1.25ms)
# CONFIG_BT_PERIPHERAL_PREF_MIN_INT=12
# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Rotary encoder configuration
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Layer LED config -------------------
CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
# CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
