CONFIG_ZMK_KEYBOARD_NAME="mona2"
# Enable USB and Bluetooth connectivity
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_ZMK_SPLIT_BLE=y

# Split keyboard configuration
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Debug logging settings
CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

# smooth scroller
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y

# Battery reporting configuration
CONFIG_ZMK_BATTERY_REPORTING=y

# Thread stack size configurations
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y



# -------------------------------------------------------------


# CONFIG_GPIO=y
# CONFIG_INPUT=y
# CONFIG_PINCTRL=y
# CONFIG_SENSOR=y


#Layer LED config -------------------
# CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
# CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
# CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y

#ZMK Studio config -------------------
# CONFIG_ZMK_STUDIO=y
# CONFIG_ZMK_STUDIO_LOCKING=n

#Bluetooth config -------------------
# CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
# CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
