manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sayu-hub
      url-base: https://github.com/sayu-hub
    - name: badjeff    # <-- PMW3610
      url-base: https://github.com/badjeff
    - name: sekigon-gonnoc  # <-- PAW3222
      url-base: https://github.com/sekigon-gonnoc
    - name: tttuemura
      url-base: https://github.com/tttuemura
    - name: caksoylar  # <-- RGB LED
      url-base: https://github.com/caksoylar  
    - name: zettaface  # <-- Input Processor Keybind
      url-base: https://github.com/zettaface
    # --- dongle ---
    - name: rschenk
      url-base: https://github.com/rschenk
    - name: BP
      url-base: https://github.com/taichan1113
    # --- dongle end ---
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    # - name: zmk-pmw3610-driver
    #   remote: badjeff
      # revision: zmk-0.3
    - name: zmk-driver-paw3222
      remote: sekigon-gonnoc
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    # - name: zmk-input-processor-keybind
    #   remote: zettaface
    #   revision: main
    # --- dongle ---
    - name: zmk-component-raytac-dongle
      remote: rschenk
      revision: v0.3
    # --- dongle end ---
  self:
    path: config
